plugins {
    id 'com.android.application'
}

android {
    namespace 'pl.piko.android'
    compileSdk 36

    defaultConfig {
        applicationId "pl.piko.android"
        minSdk 26
        targetSdk 36
        versionCode 1
        versionName "0.1.0"
    }

    buildTypes {
        debug {
            applicationIdSuffix ""
            versionNameSuffix "-test"
        }

        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
